### ISSUE TITLE
if there is way to make sure which data used as target

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pyARC#12]
it can be dangerous to train classier on wrong column of train data
then 
if there is way to make sure which data used as target
for example to add attribute to classifier 
like

dir(cba)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'algorithm', 'available_algorithms', 'clf', 'confidence', 'fit', 'maxlen', 'predict', 'predict_probability', 'rule_model_accuracy', 'support']

**Comment by jirifilip** [comment]
Hello, Sandy,

good idea. I improved the code a little bit and now you can set which target class value to train the model with and then you can check the value of the target class. 

The following code snippet should illustrate that well.

```python
from pyarc import CBA,TransactionDB
import pandas as pd

txns = TransactionDB.from_DataFrame(pd.read_csv("iris.csv"), target="sepallength")
cba = CBA()
cba.fit(txns)

print(cba.clf.rules)

print(cba.target_class)
```
