### ISSUE TITLE
predict_probability  not = confidence  ?

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pyARC#13]
seems to be predict_probability in 
cba.predict_probability(transactions)
is different from confidence of rule used for particular data observation
can you share algorithm how  predict_probability is calculated ?

**Comment by jirifilip** [comment]
Hello, 

prediction probability is calculated as a confidence of the rule that matched the data instance

```
def predict_probability(self, datacase):
        """predicts target class probablity of one 
        datacase
        """
        for rule in self.rules:
            if rule.antecedent <= datacase:
                return rule.confidence
            
        return self.default_class_confidence
```

**Comment by jirifilip** [comment]
Upon further review, I believe my implementation of `predict_probablity` is correct. In the `test` directory, you can find the unit tests for the function (`test_cba.py` file)

```python
def test_predict_probability_works(self):
        cba = CBA(algorithm="m1")

        test_dataframe = pd.read_csv(dataset_file, sep=";")
        
        transactions = TransactionDB.from_DataFrame(test_dataframe)
        transactions_test = TransactionDB.from_DataFrame(test_dataframe[:2])

        cba.fit(transactions)

        probabilities = cba.predict_probability(transactions_test)
        matched_rules = cba.predict_matched_rules(transactions_test)

        for idx in range(len(probabilities)):
            self.assertEqual(probabilities[idx], matched_rules[idx].confidence)
```

**Comment by jirifilip** [comment]
Don't be afraid to look into the code for some of the functions' implementations, I think it's quite comprehensible and well-documented.

**Comment by Sandy4321** [comment]
thanks for soon answer
let see this example from your code
header1 = ["A", "B", "Y"]
rows1 = [
    [1, 1, 0],
    [1, 1, 0],
    [1, 1, 1],
    [0, 0, 0],
    [0, 0, 1],
    [0, 0, 1]
]

transactions = TransactionDB(rows1, header1)

cba = CBA()

cba.fit(transactions)

probs1 = cba.clf.predict_probability_all(transactions)

then
cba.clf.rules
[CAR {A=1} => {Y=0} sup: 0.33 conf: 0.67 len: 2, id: 1]
probs1
[0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 0.5, 0.5, 0.5]

my guess this probability 0.5 
is for this default  rule part
    [0, 0, 0],
    [0, 0, 1],
    [0, 0, 1]
cba.clf.default_class
'1'
the default rule is if A= 0 then Y = 1
or
if B= 0 then Y = 1
it has 2 correct answers 
    [0, 0, 1],
    [0, 0, 1]
and one mistaken 
then is should be 
  [0, 0, 0],

may you help understand what 0.5 stands for 
PS
by the way what test code is for support value ?
seems to be I have some issues with support for not simple data like this one
but for more complicated data
thanks
