### ISSUE TITLE
So how to find for each row Which elementary rule matches this row

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pyARC#14]
Is there possibility to get which rule,  from discovered rule set, is responsible for classifying given one particular data sample
So how to find for each row Which elementary rule matches this row 
It can be very useful to add this functionality

**Comment by jirifilip** [comment]
Hello Sandy,

I added this functionality

```
cba = CBA(algorithm="m1")

test_dataframe = pd.read_csv(dataset_file, sep=";")
        
transactions = TransactionDB.from_DataFrame(test_dataframe)
transactions_test = TransactionDB.from_DataFrame(test_dataframe[:2])

cba.fit(transactions)

cba.predict_matched_rules(transactions_test)
```
