### ISSUE TITLE
Discretization

### ISSUE THREAD

**Issue by Vikrant77** [jirifilip/pyARC#19]
As the original 'QCBA' paper says that discretization of dataset is needed for Quantitative attributes, and 'iris.csv' dataset which is used in this repository for demonstration purpose is also discretized (inf_to_val). 

Does this repository contains code for discretization of dataset because I was unable to find the same?

**Comment by kliegr** [comment]
To better understand QCBA, you can look at the qCBA R package in CRAN, which also comes with examples and tutorials.

**Comment by jirifilip** [comment]
Hello,

this repository unfortunately does not contain the discretization functionality. It is definitely a planned feature for the future but for now, I haven't had time to implement it. 

I recommend looking for some Python packages that provide this functionality or just using [Pandas.cut](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.cut.html) functionality.

And, as @kliegr said, you can also explore the qCBA package available on CRAN.
