### ISSUE TITLE
Treatment of null values

### ISSUE THREAD

**Issue by kliegr** [jirifilip/pyARC#2]
If the dataset contains null values, the output contains rules which contain attributes referring to empty values.

**Comment by jirifilip** [comment]
This issue should now be corrected. 

```python
df = pd.read_csv("iris.csv")

# TransactionDB where NULL values are dropped
txns = TransactionDB.from_DataFrame(df)

# TransactionDB where NULL values are kept
txns_with_nulls = TransactionDB.from_Dataframe(df, drop_NaN=False)
```

The newest version isn't uploaded on PyPI yet. You can download it from github and copy it into your site_packages directory.
