### ISSUE TITLE
init file contains incorrect import

### ISSUE THREAD

**Issue by kliegr** [jirifilip/pyARC#4]
from .cba import CBA
should probably be

     from . import CBA

or

     from .CBA import CBA

(case sensitive file names on  Linux)

**Comment by jirifilip** [comment]
The issue should now be corrected. I uploaded a new version of the package on pypi. Please let me know if the issue persists.

**Comment by jirifilip** [comment]
Somehow, I still had problems with this. I found out that git isn't case sensitive so my file renames weren't working. I've corrected it now.
