### ISSUE TITLE
can you share more about algorithms used : for example about M1Algorithm, M2Algorithm

### ISSUE THREAD

**Issue by Sandy4321** [jirifilip/pyARC#7]
can you share more about algorithms used 

for example about M1Algorithm, M2Algorithm
how to find description about them in 
Liu, B. Hsu, W. and Ma, Y (1998). Integrating Classification and Association Rule Mining. Proceedings KDD-98, New York, 27-31 August. AAAI. pp 80-86.

KLIEGR, Tomas. Quantitative CBA: Small and Comprehensible Association Rule Classification Models. arXiv preprint arXiv:1711.10166, 2017.

per your code
    pred = m1clf.predict_all(txns_test)

    predM2 = m2clf.predict_all(txns_test)

 
from 
https://github.com/jirifilip/pyARC/blob/master/notebooks/extensions/benchmarks/qcba_accuracy_benchmark.ipynb

**Comment by kliegr** [comment]
M1 and M2 are two algorithmic realizations of CBA, as   described here: https://www.aaai.org/Papers/KDD/1998/KDD98-012.pdf
Both algorithms provide the same results differ in speed. 
In this paper http://ceur-ws.org/Vol-2204/paper6.pdf, we found that M1 implementation from pyARC is faster than the M2 implementation.

**Comment by Sandy4321** [comment]
I see
Thanks for references
Will try to  read
Hopefully will be able to understand ideas
Since I only started to learn this great techniques
By the way do you have some simple itroductury level description
May be something like material for students?

**Comment by kliegr** [comment]
Maybe you can refer to this tutorial: [From association rules to interpretable
classification models - a tutorial](http://ruleml.org/talks/TomasKliegr-CBARules-RuleMLWebinar-2019-04-26.pdf)
